name: playground

services:
  chapflix-api:
    container_name: chapflix2-api-container
    build:
      context: /media/idr/ExtDrive/Chapflix2
      dockerfile: /media/idr/ExtDrive/Chapflix2/infra/docker/Dockerfile.api
    ports:
      - "8043:8043"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      HOST: 0.0.0.0
    networks:
      - playground-net
    restart: unless-stopped

networks:
  playground-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
